### PR TITLE
Update scaling-deployments.md

### PR DESCRIPTION
**Pull request by MehmetFiratKomurcu**

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks @MehmetFiratKomurcu! Can you fix DCO please?

**Review by tomkerkhove — APPROVED** [review]
LGTM

**Comment by MehmetFiratKomurcu** [comment]
Hey @tomkerkhove, I don't know what DCO and LGTM mean actually but I found these commands, are these correct commands?
image

**Comment by MehmetFiratKomurcu** [comment]
Hey @tomkerkhove , I think I fixed the DCO.  Thank you.

**Comment by tomkerkhove** [comment]
Thanks a ton!

**Pull request merged**
