### PR TITLE
Added redis lag docs

### PR DESCRIPTION
**Pull request by mikelam-us**
_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes:
- Documentation added for the lag-based implementation of the redis cluster streams scaler and redis sentinel streams scaler.

Relates to https://github.com/kedacore/keda/issues/3127
Relates to https://github.com/kedacore/keda/pull/4592

### CODE REVIEW

**Comment by krishnadurai** [comment]
@tomkerkhove 
Here's the linked GitHub issue: https://github.com/kedacore/keda/issues/3127
Here's the PR addressing the issue: https://github.com/kedacore/keda/pull/4592

**Comment by tomkerkhove** [comment]
Thanks, updated PR and will wait until your feedback is incorporated

**Review by JorTurFer — COMMENTED** [review]
Could you update standalone documentation as well?

**Review by JorTurFer — APPROVED** [review]
LGTM!

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
