### PR TITLE
docs: fix minor typo in scaling-deployments main doc

### PR DESCRIPTION
**Pull request by EnriqueTejeda**
Fix a minor typo inside of scaling-deployment main docs.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

- Fix minor typo in [content/docs/2.9/concepts/scaling-deployments.md](https://github.com/kedacore/keda-docs/compare/main...EnriqueTejeda:keda-docs:fix-typo-scalers?expand=1#diff-b272fa4bd1dc40d5e2783a313f475a9d6decfccf63822797514cc65550a2e99c)

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
nice catch!
Does this apply to other versions too?

**Comment by EnriqueTejeda** [comment]
> nice catch! Does this apply to other versions too?
Thanks and sure, working on it right now 😃

**Comment by EnriqueTejeda** [comment]
> nice catch! Does this apply to other versions too?

Do it, i push a new commit with all changes 🥳

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
Thanks a lot!

**Pull request merged**
