### PR TITLE
cron scaler: clarify desiredReplicas 0

### PR DESCRIPTION
**Pull request by ecerulm**
_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

It has happened several times ([#5585], [#3609], [#1759] , [#2153], [#4474], [#3956]) that
user tries to use cron scaler with desiredReplicas set to 0 and
it doesn't work as expected. This PR adds a note to the cron scaler
to clarify that is not the right approach.

[#5585]: https://github.com/kedacore/keda/discussions/5585#discussioncomment-8719171
[#3609]: https://github.com/kedacore/keda/issues/3609
[#1759]: https://github.com/kedacore/keda/issues/1759
[#2153]: https://github.com/kedacore/keda/issues/2153
[#4474]: https://github.com/kedacore/keda/issues/4474
[#3956]: https://github.com/kedacore/keda/issues/3956

Related https://github.com/kedacore/keda/issues/5586

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Thanks for the improvement of the documentation, this has been a recurrent issue within the scaler and now is quite more clear!

As this is the behavior since the beginning, could you update other versions as well? (including the v2.14 that isn't released but docs are in the repo)

**Comment by ecerulm** [comment]
> As this is the behavior since the beginning, could you update other versions as well? (including the v2.14 that isn't released but docs are in the repo)

Done!

**Review by JorTurFer — COMMENTED** [review]
Looking good! Thanks for the improvement ❤️ 
Could you undo the change for v1.5? there are some differences related with APIs and so on and it doesn't make sense to keep updated as it's a really old version

**Comment by ecerulm** [comment]
> Could you undo the change for v1.5? there are some differences related 

@JorTurFer  done!

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
