### PR TITLE
Created Procedure for Setting Up Autoscaling with KEDA

### PR DESCRIPTION
**Pull request by shubhusion**
### Description of Changes

Created a procedure for setting up a scaler in KEDA.

### Checklist
- [x] Commits are signed with Developer Certificate of Origin (DCO)

### Issue Fixed
Fixes [kedacore/keda-docs#1368](https://github.com/kedacore/keda-docs/issues/1368)

### CODE REVIEW

**Comment by shubhusion** [comment]
Hi @JorTurFer,

Could you please review the finalized PR for #1368? The changes you specified in the previous PR #1415 have been implemented here. However, due to an issue with rebasing, I had to close the earlier PR.

Thank you!

**Review by JorTurFer — COMMENTED** [review]
Looks good to me! The only point is that we should include it also as part of v2.16 (if you rebase the branch the folder will be there).

There is another question that comes to my mind, maybe we could transform this into a getting started that we place in the getting started section instead of a versioned documentation. WDYT @tomkerkhove @zroubalik ? 
Maybe we can do it in a following PR just refactoring a bit this one (which is nice, tbh)

**Comment by shubhusion** [comment]
> Looks good to me! The only point is that we should include it also as part of v2.16 (if you rebase the branch the folder will be there).
> 
> There is another question that comes to my mind, maybe we could transform this into a getting started that we place in the getting started section instead of a versioned documentation. WDYT @tomkerkhove @zroubalik ? Maybe we can do it in a following PR just refactoring a bit this one (which is nice, tbh)

@JorTurFer Included in v2.16 also.

**Review by zroubalik — APPROVED** [review]
LGTM

@JorTurFer agree on the Getting Started Guide, I think this is something we can do as a follow up.

**Pull request merged**
