### PR TITLE
WIP - Use built-in FAQ functionality

### PR DESCRIPTION
**Pull request by tomkerkhove**
Use built-in FAQ functionality - https://about.okkur.org/syna/fragments/faq/

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Only need to fix the expanding/collapsing per question.

**Comment by anirudhgarg** [comment]
Anyway to preview the changes - other than look at the changed files ?

**Comment by jeffhollan** [comment]
The netlify check at has a details link that links to it staged. Says deploy-preview. Note that there is a bug in this and the FAQ isn’t expanding.

**Comment by tomkerkhove** [comment]
No idea how to fix this, the script doesn't kick in and I'm no frontend dev 😅

**Comment by tomkerkhove** [comment]
Closing in favor of new website

**Comment by stp-ip** [comment]
What were the specific reasons to move away from Syna? Happy to learn from your experience and at least improve Syna retrospectively.

**Comment by tomkerkhove** [comment]
We went with a custom theme, for the rest Syna was working fine - Thanks!

**Comment by stp-ip** [comment]
Great and unfortunate to see you move to a custom theme even if it looks great :)
Also welcome in the CNCF community.

**Pull request closed without merging**
