### PR TITLE
Welcome Apache Airflow as a user!

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

/cc @turbaszek

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@zroubalik The users are not listed ideally in the preview but will fix in separate PR; if I can figure it out.

**Comment by zroubalik** [comment]
@tomkerkhove do you mean this page? https://deploy-preview-207--keda.netlify.app/community/#users

**Comment by turbaszek** [comment]
I think it looks good, the Coralogix logo takes some time to load but once loaded it's ok

**Comment by tomkerkhove** [comment]
> > @zroubalik The users are not listed ideally in the preview but will fix in separate PR; if I can figure it out.
> 
> @tomkerkhove do you mean this page? [deploy-preview-207--keda.netlify.app/community/#users](https://deploy-preview-207--keda.netlify.app/community/#users)

Yes, it looks like this on my machine which is not ideal:
image

Will see if I can move them to another line or maybe it's just me.

**Comment by zroubalik** [comment]
> Will see if I can move them to another line or maybe it's just me.

@tomkerkhove same for me, it doesn't look good. But the same section on the bottom of the main page looks better (2 lines).

**Comment by ahmelsayed** [comment]
I think https://github.com/kedacore/keda-docs/pull/208 should fix that layout to match the one on the homepage

**Comment by tomkerkhove** [comment]
Thanks @ahmelsayed, it works!
image

**Comment by tomkerkhove** [comment]
PTAL @zroubalik @ahmelsayed

**Comment by tomkerkhove** [comment]
@turbaszek We are looking for KEDA end-users who want to be interviewed by CNCF for our CNCF Graduation proposal.

Are you willing to share about your experiences on using KEDA? This can be anonymously if need be.

If so, feel free to fill in https://forms.gle/91dD4RVxifWsS2hc7

**Comment by turbaszek** [comment]
Sure, I can share some insight. Additionally maybe @dimberman @ashb may help if Astronomer is still using KEDA?

**Comment by tomkerkhove** [comment]
I've reached out to them as well 🤞

Thanks!

**Pull request merged**
