### PR TITLE
Adding docs for how to override the default HTTP client timeout

### PR DESCRIPTION
**Pull request by arschles**
Ref https://github.com/kedacore/keda/pull/1251/

cc/ @tomkerkhove @zroubalik

### CODE REVIEW

**Review by tomkerkhove — COMMENTED** [review]
LGTM, only thing that would need to change is move this to v2.1 docs please

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by zroubalik** [comment]
@arschles one more small nit, could you please move this to 2.1 docs? ie. `content/docs/2.1/operate.md`

**Comment by arschles** [comment]
@zroubalik sorry for the delay - done 😄

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
