### PR TITLE
Guidance how to contribute scaler docs

### LINKED ISSUE #51: Provide new scaler template
Provide a template that can be used to document new scalers so that all scalers use a similar doc approach.

The template should come with a brief doc describing what the goal is and what should be documented.

### PR DESCRIPTION
**Pull request by tomkerkhove**
Guidance how to contribute scaler docs.

Closes #51

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Let me know what you think @melmaliacone

**Comment by tomkerkhove** [comment]
PTAL @zroubalik @ahmelsayed

**Comment by lucperkins** [comment]
@tomkerkhove I think a better way to do this would be to use [archetypes](https://gohugo.io/content-management/archetypes). I can add a scaler archetype to the new site design.

**Comment by tomkerkhove** [comment]
Now that we have `hugo new --kind scaler docs/scalers/my-new-scaler.md` we no longer need this, right @lucperkins?

**Comment by lucperkins** [comment]
@tomkerkhove That's correct, yeah. The archetype approach is a bit cleaner IMO.

**Comment by tomkerkhove** [comment]
So best to close this one in favor of new design then I guess?

**Comment by tomkerkhove** [comment]
Closing in favor of https://github.com/kedacore/keda-docs#adding-scaler-documentation

**Pull request closed without merging**
