### PR TITLE
samples link and list

### PR DESCRIPTION
**Pull request by jeffhollan**
resolves https://github.com/kedacore/keda-docs/issues/31

### CODE REVIEW

**Comment by tomkerkhove** [comment]
LGTM

One question though - Should we add a. NET sample without functions to show you can do that? Not a must though

**Comment by jeffhollan** [comment]
@tomkerkhove thought about that too. Know I want the rabbitmq cause it’s simple, functions cause it highlights that, 3rd one I wasn’t sure. I went with the one that shows how you can do jobs, but maybe .NET is more applicable? I’m ok either way.

**Comment by tomkerkhove** [comment]
Let's just stick with this then but maybe add a line before the samples where all the samples are aggregated (even though it's in the nav)

Happy to PR if you want

**Comment by jeffhollan** [comment]
Great idea. As like a subtitle

**Pull request merged**
