### PR TITLE
chore: Add databaseIndex to documentation of redis-cluster scaler

### PR DESCRIPTION
**Pull request by peschmae**
_Provide a description of what has been changed_

Add `databaseIndex` argument to documentation of `redis-cluster` scaler.
The text is identical to the `redis` scaler.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Comment by JorTurFer** [comment]
Nice!
You're right, all the redis list/stream scalers use the same library under the hood, so the behaviour should be the same. Could you update other redis docs with this change too?

**Comment by peschmae** [comment]
I just realised that there are mutliple version directories for the docs.
I've updated 2.12 in the previous commit. Should I also do 2.13 or are some changes synced between the versions?

**Comment by peschmae** [comment]
I've squashed all doc changes for 2.12 into a single commit, and made the same changes to the docs for 2.13. 

I hope it's fine like this

**Review by JorTurFer — APPROVED** [review]
LGTM! thanks for the improvement ❤️

**Pull request merged**
