### PR TITLE
Provide documentation for `accountName` for Azure Storage Queues (v2.2)

### PR DESCRIPTION
**Pull request by csnance**
It appears that the code supports passing in the accountName metadata but the docs do not currently reflect this.

### CODE REVIEW

**Review by csnance — COMMENTED** [review]
Updated wording in parameter description

**Review by tomkerkhove — APPROVED** [review]
LGTM, would you mind updating v2.0, v2.1 & v2.3 as well please?

**Comment by csnance** [comment]
> LGTM, would you mind updating v2.0, v2.1 & v2.3 as well please?

Done.

**Review by tomkerkhove — APPROVED** [review]
Thank you for your contribution! Would you mind [fixing the DCO issues](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what) please?

**Comment by csnance** [comment]
> Thank you for your contribution! Would you mind [fixing the DCO issues](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what) please?

Done.

**Pull request merged**
