### PR TITLE
chore: Remove GittiGidiyor as listed end-user given eBay has closed their business

### PR DESCRIPTION
**Pull request by tomkerkhove**
Remove GittiGidiyor as listed end-user given eBay has closed their business:

https://www.ebayinc.com/stories/news/ebay-to-close-gittigidiyor-operations/

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Relates to https://github.com/kedacore/keda-docs/pull/588

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@nilayasiktoprak can you confirm this is correct? Sorry to hear.
Do you work for eBay now or did they absorb things? Do they use KEDA?

**Review by JorTurFer — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Too fast @JorTurFer, I wanted to have @nilayasiktoprak's approval first but I guess it's OK

**Comment by JorTurFer** [comment]
f**k, sorry. Should we revert it? 😢

**Comment by tomkerkhove** [comment]
Nah it's ok - No worries!

**Comment by nilayasiktoprak** [comment]
Hey, unfortunately it's correct. However, the company Im working at right now also uses KEDA in prod, so i'll open a new PR about it :)

**Pull request merged**
