### PR TITLE
Modified vhostname to vhost in RabbitMQ Queue 

### PR DESCRIPTION
**Pull request by Shubham82**
As Per discussion [kedacore/keda/discussions#1430](https://github.com/kedacore/keda/discussions/1430). Modified the vhostname to vhost  in Rabbit MQ Queue for  more robust user experience.  

Signed-off-by: Shubham Kuchhal <shubham.kuchhal@india.nec.com>

### CODE REVIEW

**Comment by Shubham82** [comment]
@tomkerkhove could you please look into that.  i changed in 2.0 and 2.1 docs. should i also change in 1.4 and 1.5

Thanks.

**Review by coderanger — APPROVED** [review]
+1 for consistency.

**Comment by Shubham82** [comment]
Thanks @coderanger

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
