### PR TITLE
Update authentication.md with changes to azureKeyVault

### PR DESCRIPTION
**Pull request by ericyew**
Missing update to azureKeyVault with podIdentity nested under azureKeyVault as per [azure-key-vault.md](https://github.com/kedacore/keda-docs/blob/337cb437cdc5d7bbf38b18b8571f7a2ff1e23941/content/docs/2.10/authentication-providers/azure-key-vault.md)

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Comment by zroubalik** [comment]
Thanks, could you please fix this also in the upcoming 2.11 version?

**Review by zroubalik — COMMENTED** [review]
Thanks, could you please fix this also in the upcoming 2.11 version

**Comment by JorTurFer** [comment]
> Thanks, could you please fix this also in the upcoming 2.11 version

v2.9 needs to be updated too, could you update it as well?

**Comment by ericyew** [comment]
> Thanks, could you please fix this also in the upcoming 2.11 version

done

> > Thanks, could you please fix this also in the upcoming 2.11 version
> 
> v2.9 needs to be updated too, could you update it as well?

done as well

**Comment by ericyew** [comment]
Added some extra information that pod identity binding needs to be setup in the keda namespace. I spend 1.5 days troubleshotting this issue as this was not mentioned in the doco that the binding should be setup in the keda namespace and not in the app namespace where the scaledJob/Object is deployed to.

**Pull request merged**
