### PR TITLE
Add a detailed description of the "idleReplicaCount" field, along with an example.

### PR DESCRIPTION
**Pull request by mahone3297**
Related to https://github.com/kedacore/keda/issues/2314, some people discussed there.
So, I gather the keypoint infomation and write it into the docs.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes https://github.com/kedacore/keda/issues/2314

### CODE REVIEW

**Comment by mahone3297** [comment]
Is there somebody help me to review it ?

**Review by zroubalik — COMMENTED** [review]
Thank you!

Could you please update more versions?

At least 2.9, 2.10 and 2.13?

**Comment by mahone3297** [comment]
@zroubalik I have updated the code. Now it covers the version 2.9, 2.10, 2.11, 2.12, 2.13. Please review.

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
