### PR TITLE
add targetQueryValue param to postgreSQL scaler docs

### PR DESCRIPTION
**Pull request by dimberman**

### CODE REVIEW

**Comment by tomkerkhove** [comment]
LGTM but will wait for PR to be merged!

**Comment by ahmelsayed** [comment]
LGTM too. I merged the other PR.

**Comment by tomkerkhove** [comment]
@dimberman Is it correct that `targetQueryValue` should be a string?

**Comment by VojtechVitek** [comment]
I believe so: https://github.com/kedacore/keda/pull/643/files#diff-297972b04c7b8fc82074c50315b35d3dR68

**Pull request merged**
