### PR TITLE
Add Swiss Life as KEDA user

### PR DESCRIPTION
**Pull request by mac8005**
Hi.

We're using KEDA in our production environment since today 🚀.

Regards

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks a ton! 🎉🎉🎉

**Comment by tomkerkhove** [comment]
Can you fix the DCO issues please? You can learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

**Review by zroubalik — APPROVED** [review]

**Review by JorTurFer — APPROVED** [review]
Awesome!!!!!
❤️ ❤️ ❤️ ❤️

**Comment by mac8005** [comment]
> Can you fix the DCO issues please? You can learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

done

**Comment by tomkerkhove** [comment]
@mac8005 We are looking for KEDA end-users who want to be interviewed by CNCF for our CNCF Graduation proposal.

Are you willing to share about your experiences on using KEDA? This can be anonymously if need be.

If so, feel free to fill in https://forms.gle/91dD4RVxifWsS2hc7

**Pull request merged**
