### PR TITLE
Datadog: Add Required min, max and interval for HPA

### PR DESCRIPTION
**Pull request by rr-paras-patel**
Without this change HPA wouldn't work.
 Better to provide complete example rather than assuming others will read lot of other common docs

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Signed-off-by: Paras  Patel <parasprince2001@gmail.com>

### CODE REVIEW

**Comment by tomkerkhove** [comment]
What change made it work for you? None of these values should be required.

**Comment by rr-paras-patel** [comment]
Is there any default value for `maxReplicaCount` and `minReplicaCount` ? 
 Without this it was scaling replicas to 0.

**Comment by tomkerkhove** [comment]
Yes, they are documented on https://keda.sh/docs/latest/concepts/scaling-deployments/#scaledobject-spec but `0` is indeed the default for `minReplicaCount`.

**Comment by tomkerkhove** [comment]
Just out of curiosity - What was the issue you've had? Because you shouldn't have to add all of this configuration to get it working.

**Comment by rr-paras-patel** [comment]
> Just out of curiosity - What was the issue you've had? Because you shouldn't have to add all of this configuration to get it working.

if someone use metric(e.g. RPS) then service need to be there at least with replica. otherwise technically it's not possible to generate traffic and report metric.

**Comment by tomkerkhove** [comment]
THat is true, but the sample uses Redis so I don't really see why the addition is an added value over our typical ScaledObject docs?

**Pull request closed without merging**
