### PR TITLE
Make clear where the password should be in the connectionstring

### PR DESCRIPTION
**Pull request by simonrondelez**
It is not clear in the documentation where the password should be in the connection string. This PR makes this clear.

Signed-off-by: Simon Rondelez <simonrondelez@me.com>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Related GH issue https://github.com/kedacore/keda/issues/1277

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Thanks for the improvement, could you apply it for all versions? atm, you have done only for v2.3 (current version is 2.8)

**Comment by tomkerkhove** [comment]
Sorry to be a pain but would you mind reverting changes to all v1.x scaler docs please? :)

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks!

**Comment by tomkerkhove** [comment]
Can you fix the DCO issues please? You can learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

**Comment by simonrondelez** [comment]
should be good to go now :)

**Pull request merged**
