### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jjjjeeffff**
Fix 'Cloudatch' typo and update casing to match AWS.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
You can find guidance in our contributing guide if you need help.

Thanks for the PR!

**Comment by zroubalik** [comment]
@jjjjeeffff would you mind fixing this in the docs for upcoming 2.0 version?
 `content/docs/2.0/scalers/aws-cloudwatch.md`

**Comment by jjjjeeffff** [comment]
Should be all set @tomkerkhove.
2.0 docs updated as well @zroubalik - no problem!

**Comment by tomkerkhove** [comment]
Thanks!

**Pull request merged**
