### PR TITLE
fix: misleading doc that states resource (cpu/mem) scalers uses limit

### PR DESCRIPTION
**Pull request by mootpt**
Fixes https://github.com/kedacore/keda-docs/issues/1028

This scaler uses resource requests not limits.

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Could you please also fix Memory scaler?

**Comment by mootpt** [comment]
@zroubalik should be all set now

**Review by JorTurFer — APPROVED** [review]
LGTM!
Thanks for fixing this ❤️

**Review by zroubalik — COMMENTED** [review]
@mootpt thanks for the contribution, we also need you to submit the fix with proper DCO, could you please fix that?

Instructions:
https://github.com/kedacore/keda-docs/pull/1095/checks?check_run_id=12143076537
```
To add your Signed-off-by line to every commit in this branch:

    Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
    In your local branch, run: git rebase HEAD~2 --signoff
    Force push your changes to overwrite the branch: git push --force-with-lease origin request-not-limit
```

**Comment by Adarsh-verma-14** [comment]
Hi @JorTurFer @tomkerkhove  @zroubalik ,
I can see that there is no activity for this fix from some weeks so if all of you don't mind can i fix with proper DCO ?

**Comment by JorTurFer** [comment]
@mootpt, could you solve the DCO issue? You have done the work and should be who is referenced in the commit log 😄

**Comment by JorTurFer** [comment]
I close this PR as abandoned :(

**Pull request closed without merging**
