### PR TITLE
Update trigger specification section for RabbitMQ, update 'host' parameter format, to specify that it supports vhost along with subpaths too

### PR DESCRIPTION
**Pull request by AmorBielyi**
Update trigger specification section for RabbitMQ, update 'host' parameter format, to specify that it supports vhost along with subpaths too

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Relates to https://github.com/kedacore/keda/issues/2634
Relates to https://github.com/kedacore/keda/pull/4584

### CODE REVIEW

**Comment by AmorBielyi** [comment]
> I get the idea, but doesn't it make it a bit complex now? Maybe we just need to clarify in text instead of the current approach

Hi, thank you for your review, could you please clarify which exactly text I need to change?

**Comment by tomkerkhove** [comment]
I find this to be somewhat confusing: `<protocol>://<host>:<port>/[path/.../pathN]vhost`.

What do you think @JorTurFer @zroubalik?

**Comment by AmorBielyi** [comment]
> I find this to be somewhat confusing: `<protocol>://<host>:<port>/[path/.../pathN]vhost`.
> 
> What do you think @JorTurFer @zroubalik?

Thanks, what do you think about this? `<protocol>://<host>:<port>/path/vhost`

**Comment by tomkerkhove** [comment]
`<protocol>://<host>:<port>/path/vhost` or `<protocol>://<host>:<port>/<path>/vhost`?

**Comment by AmorBielyi** [comment]
> `<protocol>://<host>:<port>/path/vhost` or `<protocol>://<host>:<port>/<path>/vhost`?

The last one looks good to me

**Review by tomkerkhove — APPROVED** [review]

**Comment by rtnpro** [comment]
@AmorBielyi Could you get the changes work with the `amqp` protocol? What I realized during my test is that the `amqp` go library does not support subpath in host URI at all.

**Comment by rtnpro** [comment]
@tomkerkhove What about also documenting a host URI containing a subpath(s) without `vhost`? In that case, the subpath should end with a trailing `/`. That's what is specified in the upstream docs: https://www.rabbitmq.com/management.html#path-prefix

image

**Comment by AmorBielyi** [comment]
> 

Good idea! done

**Comment by AmorBielyi** [comment]
> @tomkerkhove What about also documenting a host URI containing a subpath(s) without `vhost`? In that case, the subpath should end with a trailing `/`. That's what is specified in the upstream docs: https://www.rabbitmq.com/management.html#path-prefix
> 
> image

Good idea! thanks, done!

**Comment by AmorBielyi** [comment]
@tomkerkhove @jupiterhub Hi, could you please review this PR related to https://github.com/kedacore/keda/pull/4584, thanks in advance!

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
nice catch, I missed it 🙇

**Comment by JorTurFer** [comment]
okey... it seems that I'm blind :/
The changes were in the wrong file, this PR updates them: https://github.com/kedacore/keda-docs/pull/1220

**Comment by AmorBielyi** [comment]
> okey... it seems that I'm blind :/ The changes were in the wrong file, this PR updates them: #1220

ouch! I apologize for this.. thanks for the quick fix, okay, I am moving now those changes but for correct 2.12. I will open a new PR once I finished

**Comment by JorTurFer** [comment]
No worries, It was my fail

**Pull request merged**
