### PR TITLE
Use External Scaler Artifact Hub URL for Links

### LINKED ISSUE #1021: Wrong url for external scaler KEDA HTTP && KEDA External Scaler for Azure Cosmos DB.
Links of external scalers (KEDA HTTP && KEDA External Scaler for Azure Cosmos DB) are not working on this page -https://keda.sh/docs/2.9/scalers/ 

### Expected Behavior
The links should direct to -
for KEDA  HTTP - https://github.com/kedacore/external-scalers/tree/main/artifacthub
for KEDA External Scaler for Azure Cosmos DB - https://github.com/kedacore/external-scalers/tree/main/artifacthub

### Actual Behavior
The links are directing here -
for KEDA HTTP - https://github.com/kedacore/external-scalers/artifacthub
for KEDA External Scaler for Azure Cosmos DB - https://github.com/kedacore/external-scalers/artifacthub

### PR DESCRIPTION
**Pull request by wsugarman**
This Pull Request fixes the URL used when exploring [KEDA external scalers](https://keda.sh/docs/2.9/scalers/). Today, the URLs use the "repository url" which may often be an invalid destination based on the format specified in the [Artifact Hub docs](https://artifacthub.io/docs/topics/repositories/keda-scalers/). Instead, this PR changes the URL to point to the scaler's page on Artifact Hub.

For example, the URL for my scaler `https://artifacthub.io/packages/keda-scaler/wsugarman-keda-scalers/durabletask-azurestorage-scaler` is created by:
1. Fetching the search results from Artifact Hub: `https://artifacthub.io/api/v1/packages/search?kind=8&sort=relevance`
2. Parsing the element:
```json
{
  "package_id": "fc1de730-37bc-4375-b0e1-a032c67f2537",
  "name": "durabletask-azurestorage-scaler",
  "normalized_name": "durabletask-azurestorage-scaler",
  "logo_image_id": "4727dfc7-c877-4b5c-81b5-0c8115d54e81",
  "stars": 1,
  "display_name": "Durable Task KEDA External Scaler",
  "description": "A KEDA external scaler for the Durable Task Azure Storage backend",
  "version": "1.0.0",
  "app_version": "1.0.0",
  "license": "MIT",
  "deprecated": false,
  "signed": false,
  "security_report_summary": {
    "low": 0,
    "high": 0,
    "medium": 5,
    "unknown": 0,
    "critical": 1
  },
  "all_containers_images_whitelisted": false,
  "production_organizations_count": 0,
  "ts": 1677898500,
  "repository": {
    "url": "https://github.com/wsugarman/charts/artifacthub",
    "kind": 8,
    "name": "wsugarman-keda-scalers",
    "official": false,
    "user_alias": "wsugarman",
    "display_name": "OSS KEDA External Scalers",
    "repository_id": "f9f33959-9a62-4648-bdc1-04e5e62518a7",
    "scanner_disabled": false,
    "verified_publisher": true
  }
}
```
3. Creating the URL based on `result.repository.name` and `result.normalized_name` -> ``https://artifacthub.io/packages/keda-scaler/${result.repository.name}/${result.normalized_name}``

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #1021

### CODE REVIEW

**Comment by JorTurFer** [comment]
Thanks for the fix! The preview generation is failing https://app.netlify.com/sites/keda/deploys/6403af46ce147b00086e6e46
Could you take a look?

**Comment by wsugarman** [comment]
> Thanks for the fix! The preview generation is failing https://app.netlify.com/sites/keda/deploys/6403af46ce147b00086e6e46 Could you take a look?

Sure, I'll take a look. Although I'm not much of a front-end dev, I'll see if I can make sense of it

**Comment by wsugarman** [comment]
Probably better Javascript engineers can explain why, but I was having issues with template literals. But once I just built the URL string using concatenation, it worked as expected both locally and in CI

**Review by tomkerkhove — APPROVED** [review]
Works like a charm - Thanks!

**Comment by tomkerkhove** [comment]
I love GitHub - Suddenly it collapsed a pane which turned the merge button in to a close 😄

**Pull request merged**
