### PR TITLE
docs: Provide emphasize on ignoring idleReplicaCount by default

### PR DESCRIPTION
**Pull request by RomanDvorsky**
Added anchor for each property, updated the default value for `idleReplicaCount`

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, can you update v2.7 and [fix DCO](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what) please?

**Review by arschles — APPROVED** [review]

**Review by zroubalik — COMMENTED** [review]
Looking good, just the things mentioned by Tom

**Comment by RomanDvorsky** [comment]
How can I perform the DCO — DCO - I have created the pull request from the browser so I do not have given sources locally...

**Comment by tomkerkhove** [comment]
Unfortunately this is not supported in the browser and you will have to pull the repo. If that is a problem ,then we will have to merge in a temporary branch and do it for you.

Regardless, can you update the other version as well please?

**Comment by RomanDvorsky** [comment]
well, I'm quite a newbie in GitHub so is there a simple way how can I checkout this PR branch locally - maybe some git command?

also if there is a quick way how to fix that DCO and then I can update also other versions - I do not like work for nothing.. ;)

**Comment by tomkerkhove** [comment]
What you'll need to do is:
1. Fork the repo into your account
2. Go to your fork repo
3. Clone locally

image

For fixing DCO, you can use the link that I've mentioned above

**Comment by RomanDvorsky** [comment]
totally messed it up and created new PR https://github.com/kedacore/keda-docs/pull/652

**Pull request closed without merging**
