### PR TITLE
codespell corrections

### PR DESCRIPTION
**Pull request by robin-wayve**
After noticing a couple of minor spelling errors I ran `codespell -w content/docs` (https://github.com/codespell-project/codespell).

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]

**Comment by robin-wayve** [comment]
@tomkerkhove there were a few spelling corrections in the blog posts too if you'd like a PR for those? 😄

**Comment by tomkerkhove** [comment]
Sure thing, thanks for helping!

**Comment by tomkerkhove** [comment]
Is this something we can add to a CI to block if there are issues?

**Comment by robin-wayve** [comment]
> Is this something we can add to a CI to block if there are issues?

I have used it in CI before -- it works nicely either as something to block bad spelling or to at least make suggestion comments.

**Comment by tomkerkhove** [comment]
Great, are you willing to contribute that as well?

**Comment by robin-wayve** [comment]
I may not have time in the near future, but it is already packaged as a github action if you'd like to try that: https://github.com/codespell-project/actions-codespell

**Comment by tomkerkhove** [comment]
Thank you! Opened https://github.com/kedacore/keda-docs/pull/483

**Pull request merged**
