### PR TITLE
Update the links for RabbitMQ Queue

### PR DESCRIPTION
**Pull request by Shubham82**
Signed-off-by: Shubham82 <shubham.kuchhal@india.nec.com>

Update the links for rabbitmq in authentication.md file in keda docs of 1.4, 1.5 and 2.0.

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @tomkerkhove @zroubalik 
Could you please take a look.
Thanks.

**Review by tomkerkhove — COMMENTED** [review]
LGTM, can you also update the 2.1 docs please?

**Comment by Shubham82** [comment]
Thanks @tomkerkhove  for taking look in this.

Sure i will do it, I just want confirmation should i mention the link of keda 2.0(latest)  in 2.1 docs. or should i use  **https://keda.sh/docs/2.1/scalers/rabbitmq-queue/** (if use this in future for 2.1)

**Comment by tomkerkhove** [comment]
Using 2.1 for 2.1 is ok, thanks!

**Comment by Shubham82** [comment]
ok, i will update it for 2.1 also , thanks.

**Comment by Shubham82** [comment]
Hi @tomkerkhove  i have updated for 2.1 also. PTAL.
Thanks

**Review by tomkerkhove — APPROVED** [review]
Thanks!

**Pull request merged**
