### PR TITLE
feat: Provide spellchecking

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

Provide spellchecking of docs.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)

Fixes #

### CODE REVIEW

**Comment by robin-wayve** [comment]
I think you will want an ignore file that contains
```
aks
iam
```
as these are used legitimately in your docs to refer to Azure Kubernetes Service and Identity and Access Management more often than you'll misspell "ask" and "I am". 👍🏻

**Comment by tomkerkhove** [comment]
Why is that?

**Comment by robin-wayve** [comment]
> Why is that?

This is the current output
```
> codespell **/*.md
archetypes/scaler.md:26: IAM ==> I AM, AIM
content/docs/1.4/concepts/authentication.md:185: IAM ==> I AM, AIM
content/docs/1.4/scalers/aws-cloudwatch.md:40: IAM ==> I AM, AIM
content/docs/1.4/scalers/aws-cloudwatch.md:46: IAM ==> I AM, AIM
content/docs/1.4/scalers/aws-kinesis.md:35: IAM ==> I AM, AIM
[...]
content/docs/2.0/scalers/azure-log-analytics.md:131: aks ==> ask
content/docs/2.0/scalers/azure-log-analytics.md:289: AKS ==> ASK
```
and so on

**Comment by tomkerkhove** [comment]
I need to fix the path then, because it's not finding anything :D

**Comment by robin-wayve** [comment]
or put another way: these are false-positives, and there will almost certainly be more that you'll want to add in future.

**Comment by robin-wayve** [comment]
> I need to fix the path then, because it's not finding anything :D

might be because it only checks changed files on pull requests but I'm not sure: try editing a markdown file with a deliberate error too.

**Pull request closed without merging**
