### PR TITLE
Fix:Introduce latest version for FAQ & troubleshooting.

### PR DESCRIPTION
**Pull request by Shubham82**
Add link for faq and troubleshooting links to redirect the latest docs. and update the link in README.md and also modified the content of Working with documentation versions.
Fix: #362
Signed-off-by: Shubham Kuchhal <shubham.kuchhal@india.nec.com>

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @tomkerkhove @zroubalik
Could you please take a look
Thanks.

**Comment by tomkerkhove** [comment]
Awesome! Now that we are doing it, can you do the same for:
- https://keda.sh/operate/
- https://keda.sh/concepts/
- https://keda.sh/deploy/

Of course, if you are up for it!

**Comment by Shubham82** [comment]
Thanks @tomkerkhove 

Sure, i will do that.

**Comment by Shubham82** [comment]
Addressed the comments. PTAL

> Awesome! Now that we are doing it, can you do the same for:
> 
> * https://keda.sh/operate/
> * https://keda.sh/concepts/
> * https://keda.sh/deploy/
> 
> Of course, if you are up for it!

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks a ton!

**Pull request merged**
