### PR TITLE
IM on Kubernetes Slack

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

Closes #436

### CODE REVIEW

**Comment by jeffhollan** [comment]
We should likely include the link to sign up for the K8s slack channel as can be tricky to know how to get one. Also should we add your google calendar subscription link too?

**Comment by tomkerkhove** [comment]
Calendar is open for review at #52

Can you elaborate on the Kubernetes Slack comment please? Not sure if I'm following as the change includes the link.

**Comment by zroubalik** [comment]
@tomkerkhove https://kubernetes.slack.com/messages/CKZJ36A5D

**Comment by tomkerkhove** [comment]
Oh you mean link to the channel itself?

**Comment by jeffhollan** [comment]
No on the contrib guide I have a link to sign up for access to the slack channel

**Comment by jeffhollan** [comment]
Oh maybe it’s that link. Hahaha I can’t remember

**Comment by tomkerkhove** [comment]
I got it from the contributor guide so must be that one :D

Added link to channel directly as well

**Pull request merged**
