### PR TITLE
fix: Scalers not shown on landing page #1314

### LINKED ISSUE #1314: Scalers not shown on landing page
### Report

Landing page scalers list is broken and does not show the type of scaler.
image

It seems to me that the CSS is broken, it is configured to display: none 
If I disable that, it shows as expected.
image

### Expected Behavior

Correct presentation of scaler list.
image

### Actual Behavior

Only footer of scaler card is shown
image

### Steps to Reproduce the Problem

1. Go on https://keda.sh/
2. Scroll down 
3. Look at scalers

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

### Scaler Details

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by maxiangelo**
Remove bugged feature that causes scaler cards to load incorrectly.

Fixes #1314

### CODE REVIEW

**Comment by tomkerkhove** [comment]
This is going to break @thisisobate's recent change. @thisisobate care to help fix this issue please?

**Comment by thisisobate** [comment]
@tomkerkhove Sure, will take a look at this and try to push a fix soon

**Comment by thisisobate** [comment]
Here's a fix: #1319
@tomkerkhove @maxiangelo

**Comment by tomkerkhove** [comment]
This was fixed by @thisisobate, thanks!

**Pull request closed without merging**
