### PR TITLE
Update helm install steps

### PR DESCRIPTION
**Pull request by thepaulmacca**
Signed-off-by: Paul McDonald <pm@thepaulmacca.com>

Just a quick docs update to the `helm install` commands

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

### CODE REVIEW

**Comment by JorTurFer** [comment]
hey!
thanks for the contribution! What would you like to achieve with this change? I mean, the organization is kedacore.

**Comment by tomkerkhove** [comment]
I think both options are OK, but think kedacore is better to show that it's more than keda itself

**Comment by JorTurFer** [comment]
Yes, I think KEDA is also correct, but as you say, the repo has more charts than KEDA, thanks for the clarification

**Comment by thepaulmacca** [comment]
I just found it a bit confusing, as when I go to `Releases`, the commands are different

It's up to you both really

**Comment by JorTurFer** [comment]
I'll review the releases then, maybe that's wrong. Thanks for pointing it

**Comment by JorTurFer** [comment]
you are totally right. I'm going to solve it right now.
Thanks again ❤️

**Comment by JorTurFer** [comment]
I have updated the already existing releases to show the correct commands and I have created another PR fixing [the release template](https://github.com/kedacore/charts/pull/314). I'll close this PR because it's not needed, but thanks again for pointing the issue ❤️❤️

**Pull request closed without merging**
