### PR TITLE
Update document for adding SSL support to RabbitMQ scaler

### PR DESCRIPTION
**Pull request by ansonauhk**
Document update for https://github.com/kedacore/keda/pull/1051
Signed-off-by: ansonauhk <ansonau@gmail.com>

### CODE REVIEW

**Comment by tomkerkhove** [comment]
THanks for the docs, but this will be part of v2.

Can you please make the required changes there? Sorry for the inconvenience.

**Comment by ansonauhk** [comment]
> THanks for the docs, but this will be part of v2.
> 
> Can you please make the required changes there? Sorry for the inconvenience.

It's ok. Do you want me to revert change under 1.5.1 as well?

**Comment by tomkerkhove** [comment]
Preferably yes, thanks!

**Comment by ansonauhk** [comment]
> Preferably yes, thanks!

Done

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
LGTM but will leave it up to @ahmelsayed @zroubalik based on implementation

**Comment by tomkerkhove** [comment]
In meantime, can you fix DCO issues please?

This should help you with that: https://github.com/kedacore/keda/blob/v2/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work

**Comment by tomkerkhove** [comment]
Any update on this @ansonauhk?

**Comment by tomkerkhove** [comment]
Any update on this @ansonauhk?

**Comment by leonids2005** [comment]
Any update on this feature?? It's a shame that there is still no SSL support for RabbitMQ scaler :(

**Comment by zroubalik** [comment]
@leonids2005 feel free to contribute this feature, seems like the original contributor is no longer available 🤷‍♂️ 

Closing this as the code related PR is closed as well

**Comment by leonids2005** [comment]
is the original PR available? IT will be easier to start with something already available?

**Comment by tomkerkhove** [comment]
PR was on https://github.com/kedacore/keda/pull/1051 (see above)

**Pull request closed without merging**
