### PR TITLE
Add Sharry as KEDA user

### PR DESCRIPTION
**Pull request by besanek**
Signed-off-by: Robert Jelen <robert.jelen@sharry.tech>

Add Sharry as KEDA user

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
Thank you for using KEDA!

**Comment by JorTurFer** [comment]
Welcome to the family!

**Comment by zroubalik** [comment]
Díky :)

**Comment by tomkerkhove** [comment]
Hi - We are looking for KEDA end-users who want to be interviewed by CNCF for our CNCF Graduation proposal.
Are you willing to share about your experiences on using KEDA? This can be anonymously if need be. 
If so, feel free to fill in https://forms.gle/91dD4RVxifWsS2hc7

**Pull request merged**
