### PR TITLE
Support Pod Identity for Event Hub

### PR DESCRIPTION
**Pull request by eashi**
This explains how to configure Event Hub scaler to use Pod Identity.

### CODE REVIEW

**Comment by eashi** [comment]
wrong target, sorry.

**Review by tomkerkhove — COMMENTED** [review]
LGTM, but as discussed on Slack; can you move it to 2.1 please?

**Comment by zroubalik** [comment]
@eashi could you please rebase this against 2.1?

**Comment by eashi** [comment]
I changed it so it is on 2.1.

**Review by tomkerkhove — APPROVED** [review]

**Review by zroubalik — APPROVED** [review]
Thanks!

**Pull request merged**
