### PR TITLE
Add analytics

### PR DESCRIPTION
**Pull request by chalin**
Contributes to #594 by adding analytics support. I'm investigating how best to bring in the cookie-consent scripts, styles and Hugo partials. Hopefully you'll agree that we can do this in two steps (with a small window of time between the two).

/cc @nate-double-u

### CODE REVIEW

**Comment by chalin** [comment]
> Can you fix the DCO

Done.

**Comment by tomkerkhove** [comment]
There we go!

**Comment by tomkerkhove** [comment]
> I'm investigating how best to bring in the cookie-consent scripts, styles and Hugo partials. Hopefully you'll agree that we can do this in two steps (with a small window of time between the two).

No problem at all.

Would you mind sharing how maintainers can get access to the Google Analytics information please?

**Comment by chalin** [comment]
> Would you mind sharing how maintainers can get access to the Google Analytics information please?

Yes. I'm looking into options and will let you know soon.

**Pull request merged**
