### PR TITLE
feat: Add support for SAS tokens for authentication in Azure Service …

### PR DESCRIPTION
**Pull request by v-shenoy**
…Bus scaler.

Signed-off-by: Vighnesh Shenoy <vshenoy@microsoft.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Relates to https://github.com/kedacore/keda/issues/2920

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
LGTM! ❤️

**Comment by tomkerkhove** [comment]
Let's make sure the feature gets merged ASAP to keep it in sync :D

**Comment by JorTurFer** [comment]
There is no feature to merge, I added support to it as side effect when I migrated the SDK xD

**Comment by tomkerkhove** [comment]
Yes there is - https://github.com/kedacore/keda/pull/3673

**Comment by JorTurFer** [comment]
It's only to update the changelog, the feature itself is ready xD

**Pull request merged**
