### PR TITLE
Freepik Company, new KEDA User

### PR DESCRIPTION
**Pull request by Roman-GA**
_Provide a description of what has been changed_
Freepik Company Keda user
### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, thank you for using KEDA!

Would you mind fixing DCO issues please? You can learn more in our contributionguide.

**Review by zroubalik — APPROVED** [review]
Awesome 🎉

**Comment by Roman-GA** [comment]
> LGTM, thank you for using KEDA!
> 
> Would you mind fixing DCO issues please? You can learn more in our contributionguide.

its been fixed thanks!

**Comment by Roman-GA** [comment]
> LGTM, thank you for using KEDA!
> 
> Would you mind fixing DCO issues please? You can learn more in our contributionguide.

its been fixed,  thanks!

**Comment by JorTurFer** [comment]
Welcome!!!

**Comment by tomkerkhove** [comment]
@rga-atl We are looking for KEDA end-users who want to be interviewed by CNCF for our CNCF Graduation proposal.

Are you willing to share about your experiences on using KEDA? This can be anonymously if need be.

If so, feel free to fill in https://forms.gle/91dD4RVxifWsS2hc7

**Pull request merged**
