### PR TITLE
Welcome Astronomer, a new KEDA user & partner!

### PR DESCRIPTION
**Pull request by tomkerkhove**
Welcome Astronomer, a new KEDA user!

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Ok for you @dimberman?

**Comment by dimberman** [comment]
@tomkerkhove thank you for taking this up :). Could we add astronomer as "community" cc: @jeffhollan 

Also when I went to the preview page on netlify the image appeared to be broken? I have some assets from our designers that I can add if you'd like.

**Comment by tomkerkhove** [comment]
I'll add you to both maybe, what do you think @jeffhollan?

Feel free to share designs, will fix the image tomorrow. Was in a hurry!

**Comment by jeffhollan** [comment]
Yep both is great! We ❤️ Astronomer.io

**Pull request merged**
