### PR TITLE
Procedure for Setting up a Scaler

### LINKED ISSUE #1368: Write a Procedure for Setting Up a Scaler
Write a procedure for setting up a scaler for KEDA. Include all steps that are common to any scaler. Supplemental instructions specific to particular scalers can be elsewhere.

This procedure is fundamental to using KEDA and should go at or near the beginning of the Operator's Guide.

### Use-Case

Setting up a scaler seems to be largely a matter of installing the scaler and providing parameters in a configuration file. While the configurations are provided for all the various scalers, there doesn't seem to be a description of the procedure for doing the basic setup. This should go at the top of the Operator guide. 

Users should be able to follow the procedure for any (or at least most) scalers. Any scaler that requires special instructions other than the configuration file should have its own procedure page, listing the extra steps required.

### Specification

Write complete, step-by-step instructions. Don't assume the user knows anything. For example, name the configuration file and tell users where to put it, even if this is common knowledge. This is the generic template they'll use to set up any scaler, including their first.

### PR DESCRIPTION
**Pull request by shubhusion**
_Provide a description of what has been changed_

Created a Procedure for Setting up a Scaler in KEDA

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #1368

### CODE REVIEW

**Comment by shubhusion** [comment]
@zroubalik i have made the PR but the above checks are failing. can you help me in resolving it ?

**Comment by tomkerkhove** [comment]
This is because the build is failing, see: https://github.com/kedacore/keda-docs/pull/1408#issuecomment-2171820627

**Comment by shubhusion** [comment]
> This is because the build is failing, see: [#1408 (comment)](https://github.com/kedacore/keda-docs/pull/1408#issuecomment-2171820627)

build is failing bacause it is not able to find the images I had attached as output.

**Comment by shubhusion** [comment]
@tomkerkhove I will make another PR. I am closing it.

**Pull request closed without merging**
