### PR TITLE
chore: fix scaler search to avoid excess API calls

### LINKED ISSUE #840: debounce scaler search input
Once the user starts typing the search keyword we are making an API call for each of the characters. This is not ideal. We can optimize and reduce the count of API calls by implementing a debounce logic.
## Expected Behavior
Less API calls per search keyword

## Actual Behavior
API call per keyword character

## Steps to Reproduce the Problem

  1. navigate to the scaler page
  2. Enter a sentence in the scaler search input
  3. Notice how the results changes per keystroke

## Specifications

  - **KEDA Version:** *Please elaborate*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *Please elaborate*
  - **Scaler(s):** *Please elaborate*

### PR DESCRIPTION
**Pull request by thisisobate**
_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #840

### CODE REVIEW

**Comment by thisisobate** [comment]
@tomkerkhove

**Comment by tomkerkhove** [comment]
I don't know frontend code so will leave it up to @chalin

**Review by chalin — APPROVED** [review]
Nice! 🎉 

I'd vote for, say, a 300ms debounce delay.

E.g., for context, see [How long should you debounce text input](https://stackoverflow.com/questions/42361485/how-long-should-you-debounce-text-input).

**Review by chalin — APPROVED** [review]

**Comment by chalin** [comment]
@tomkerkhove et all: we need one more approval. Thx

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
