### PR TITLE
Welcome Reddit, a new KEDA end-user!

### PR DESCRIPTION
**Pull request by tomkerkhove**
Welcome Reddit, a new KEDA end-user!

Opening PR for @isugimpy, please acknowledge in a comment that we have permissions to put the logo up.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

### CODE REVIEW

**Comment by isugimpy** [comment]
Confirmed!  Reddit is a KEDA user and we're fine with having this added.  Appreciate you opening the PR on my behalf!

**Review by zroubalik — APPROVED** [review]
🎉

**Comment by tomkerkhove** [comment]
Thank YOU @isugimpy!

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
🥳

**Pull request merged**
