### PR TITLE
Welcome Grab, a new KEDA user!

### PR DESCRIPTION
**Pull request by CtrlAltDft**
Signed off by Karan Kamath - karan.kamath@grab.com

FYI @dttung2905

### CODE REVIEW

**Comment by dttung2905** [comment]
@zroubalik This is what I mentioned about the other day. Could you help to review it ? 

Thanks Thang for helping with the PR 😜

**Review by tomkerkhove — COMMENTED** [review]
Thank you for using KEDA!

Can you fix the DCO issues please? You can learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

**Review by tomkerkhove — APPROVED** [review]
Thank you for using KEDA!

Can you fix the DCO issues please? You can learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

**Comment by JorTurFer** [comment]
You can see the steps to fix DCO in the check link: 
image

image

**Comment by CtrlAltDft** [comment]
Thank you both for the guidance 🙏 I have fixed the DCO check. There is one last required check that has been stuck for quite some time `Mixed content - keda`, is there anything I can do to fix it?

**Comment by zroubalik** [comment]
> @zroubalik This is what I mentioned about the other day. Could you help to review it ?
> 
> Thanks Thang for helping with the PR 😜

Awesome! 🚀

**Review by zroubalik — APPROVED** [review]
Welcome!

**Comment by zroubalik** [comment]
> Thank you both for the guidance 🙏 I have fixed the DCO check. There is one last required check that has been stuck for quite some time `Mixed content - keda`, is there anything I can do to fix it?

Ignore it :)

**Comment by CtrlAltDft** [comment]
Thank you :)

**Comment by JorTurFer** [comment]
❤️

**Pull request merged**
