### PR TITLE
Add minReplicaCount to scaling-jobs

### PR DESCRIPTION
**Pull request by guilhem**
Linked to https://github.com/kedacore/keda/pull/1752

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Is this missing in previous versions as well or not?

**Comment by guilhem** [comment]
@tomkerkhove not for my usage because azure pipeline is only implemented for 7 days ^^

**Comment by tomkerkhove** [comment]
No worries! I've checked and this is also missing in 2.0->2.3, can you update all versions please?

Thanks!

**Comment by tomkerkhove** [comment]
Oh this is new, I thought we already had this - Sorry and nevermind my comment above!

**Comment by guilhem** [comment]
https://github.com/kedacore/keda/pull/1752 is closed for the moment

**Pull request closed without merging**
