### PR TITLE
Feat: Provide filtering capabilities for scalers

### LINKED ISSUE #412: Improve scaler catalog to be more user-friendly
Over time, our scaler catalog has grown a lot over the last couple of releases where we have more than 30 of them today.

As a user, it's not that easy anymore to find the scalers you need and the navigation is not able to coop with it.

It would be good if we can:
- Make the navigation be more user-friendly in this case
- Integrate external scalers from the community to create a central place for all scalers (built-in or 3rd party)
- Provide filtering on the current overview, examples are:
  - Categories (ie messaging, databases, CI/CD)
  - Cloud (Alibaba, AWS, Azure, etc.)
  - Built-in / External
  - Maintainer (ie KEDA, community, ...)
  - Support for (cluster) trigger authentication?

### PR DESCRIPTION
**Pull request by thisisobate**
Todo
- [x] provide filter button on mobile
- [x] Annotate existing scalers with metadata for easier filtering

Relates to #412

### CODE REVIEW

**Comment by thisisobate** [comment]
cc: @tomkerkhove

**Comment by tomkerkhove** [comment]
I was waiting with reviewing because there was a TODO :) Doing that now!

**Comment by thisisobate** [comment]
> This takes up a big chunck of the scaler area

This is because bulma spacing selectors automatically allocate that much space for columns. I can try using vanilla css instead to reduce the spacing so the scaler cards can fit comfortably.

**Comment by thisisobate** [comment]
@tomkerkhove any updates on [this](https://github.com/kedacore/keda-docs/issues/1401)?

**Comment by tomkerkhove** [comment]
Btw, can we align the external vs built-in filter in to this new model please? Now we have 2 flavors

**Comment by thisisobate** [comment]
> No not for now, but I don't think this should block this PR, does it?

I agree. It doesn't block it. In that case, I think we should merge and close this issue.

**Comment by tomkerkhove** [comment]
> Btw, can we align the external vs built-in filter in to this new model please? Now we have 2 flavors

We need to do this first though

**Comment by thisisobate** [comment]
> Btw, can we align the external vs built-in filter in to this new model please? Now we have 2 flavors

What exactly do you mean? The "maintainer" filter option already supports the built-in and external scalers. E.g, to filter the maintainer "JensWalter", you need to switch to the `external` tab.

If you are saying we should add a new "built-in scaler" and "external scaler" filter options in the new filter pane, then I don't think that would work. Moreover, I don't think it's necessary given we already designed the ux and data architecture to work for the existing UI structure.

**Comment by tomkerkhove** [comment]
> If you are saying we should add a new "built-in scaler" and "external scaler" filter options in the new filter pane, then I don't think that would work. Moreover, I don't think it's necessary given we already designed the ux and data architecture to work for the existing UI structure.

I tend to disagree though, we currently have 2 UX for filtering scalers which is confusing. Certainly if we'll start adding more filters

**Comment by thisisobate** [comment]
> we currently have 2 UX for filtering scalers

You have a point. If we must go the route you suggest, then it would warrant a complete overhaul of the data architecture which is an additional workload and frankly, it's slightly out of scope. 

I will have to discuss with @nate-double-u internally and see what we can do about this. In the meantime, I would advise you open a new issue for this request.

Thank you!

**Comment by tomkerkhove** [comment]
Let's keep this open, it's better to keep the current experience rather than introducing two different UXes.

Why would this alignment cause a complete data architecture overhaul?

**Comment by thisisobate** [comment]
> Why would this alignment cause a complete data architecture overhaul?


Because for this to work, we would have to generate one central
datastore/index to query both in-built and external scalers which might be
tricky to solve.

We can keep this open. I will try and see if I can get something working;
will keep you posted.

cc: @nate-double-u

**Comment by thisisobate** [comment]
@tomkerkhove PTAL

**Comment by tomkerkhove** [comment]
A lot better, thank you!

image

One last ask: Can we change the order so that we show, "Type", "Category", "Maintainer" please?
Any other remarks @kedacore/keda-maintainers?

**Comment by thisisobate** [comment]
@tomkerkhove I think we're good to go 😀

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Thank you!

**Pull request merged**
