### PR TITLE
resolving broken links issues in scaling-jobs.md

### PR DESCRIPTION
**Pull request by Ritikaa96**
Signed-off-by: Ritikaa96 <ritika@india.nec.com>

Updated the broken links in scaling-jobs.md for scaledobject_types.go

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thansk for the PR! We are actually fixing them in https://github.com/kedacore/keda-docs/pull/336 already

**Comment by tomkerkhove** [comment]
But thanks for your contribution!

**Comment by Ritikaa96** [comment]
> Thanks for the PR! We are actually fixing them in #336 already
Ah great! I just saw it. sorry for not seeing that before.

**Comment by tomkerkhove** [comment]
No worries at all and sorry for not being able to help; thanks for the contribution anyway!

**Pull request closed without merging**
