### PR TITLE
change tls values from true/false to enable/disable

### PR DESCRIPTION
**Pull request by gunniwho**
Signed-off-by: Gunnar Palsson <gunniwho@gmail.com>

_Provide a description of what has been changed_

Changed the tls values from true/false to enable/disable. This is accompanying my PR to allow `disable` as a valid value [here](https://github.com/kedacore/keda/pull/2611).

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes https://github.com/kedacore/keda/issues/2608
Related https://github.com/kedacore/keda/pull/2611

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, but this does not seem to be a recent change but rather stale docs. Would you mind updating the previous versions of this?

**Comment by gunniwho** [comment]
> LGTM, but this does not seem to be a recent change but rather stale docs. Would you mind updating the previous versions of this?

done

**Review by zroubalik — APPROVED** [review]
Thanks!

**Review by arschles — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Waiting for feature to be merged first

**Comment by JorTurFer** [comment]
thanks for your contribution!

**Pull request merged**
