### PR TITLE
docs: Introduce Snowflake as partner represented by @jeffhollan

### PR DESCRIPTION
**Pull request by tomkerkhove**
Introduce Snowflake as partner represented by @jeffhollan.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@jeffhollan Feel free to approve if the logo is correct

**Review by JorTurFer — APPROVED** [review]

**Comment by jeffhollan** [comment]
Kicked off thread with Snowflake legal - will circle back when I hear back

**Comment by jeffhollan** [comment]
Unfortunately right now Snowflake has a fairly strict logo usage policy and wants to decline surfacing here for now. I'll circle back in a few weeks / months to re-submit the request. Thanks for spinning this up though @tomkerkhove

**Comment by JorTurFer** [comment]
😢

**Comment by tomkerkhove** [comment]
No worries and thanks for checking @jeffhollan !

**Pull request closed without merging**
