### PR TITLE
Provide info on our KEDA dashboard

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide info on our KEDA dashboard as a feature and how to deploy it.

Deployment is minimal for now until we have a Helm chart which should be our recommended approach. Once we have that, we can update the docs or provide a dedicated deployment page for that.

Relates to https://github.com/kedacore/keda/issues/167

### CODE REVIEW

**Comment by jeffhollan** [comment]
I'm gonna re-open just with the dashboard changes

**Comment by tomkerkhove** [comment]
Is it on purpose that we didn't include how to deploy the dashboard?

**Comment by tomkerkhove** [comment]
Thanks for merging the feature already!

**Comment by jeffhollan** [comment]
Ah no sorry. I saw conflicts from the deploy doc and assumed we both just added link to file issues but see you also added info on dashboard. We should add that back in. Feel free to merge that in or I can later too. Thanks for catching.

**Pull request closed without merging**
