### PR TITLE
Make the example for Cron Scaler match the screenshot

### PR DESCRIPTION
**Pull request by ecerulm**
The example now match the screenshot 

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
I like it, great, could you please also fix other versions? Thanks

**Comment by ecerulm** [comment]
> I like it, great, could you please also fix **other versions**? Thanks

I'm not sure I understand what you meant,  I update the other example the one about having same `start` and `end`, but I have the feel that that is probably not what you meant by "**other versions**".

**Comment by zroubalik** [comment]
You fixed this in version 2.13, would be great if we can fix this also in other version (2.14, 2.12,...)

**Comment by ecerulm** [comment]
> You fixed this in version 2.13, would be great if we can fix this also in other version (2.14, 2.12,...)

Got you now,  I added the changes in all other versions now.

**Review by zroubalik — APPROVED** [review]
Thanks!

**Pull request merged**
