### PR TITLE
Handle multiple namespaces for existing CRD delete/patch

### PR DESCRIPTION
**Pull request by kasadaamos**
Require to remove CRD's from all namespaces, otherwise they could be missed.

Signed-off-by: Amos Shapira <120427255+kasadaamos@users.noreply.github.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Comment by kasadaamos** [comment]
Actually it's more involved - when specifying resources in multiple namespaces, the name space has to be provided too. This turns into:
```
kubectl delete \
  $(kubectl get scaledobjects.keda.sh,scaledjobs.keda.sh -A \
  -o jsonpath='{"-n "}{.items[*].metadata.namespace}{" "}{.items[*].kind}{"/"}{.items[*].metadata.name}{"\n"}'\
)
```
Which I'm not sure how to include nicely in the document.

**Review by tomkerkhove — COMMENTED** [review]
Good addition, would you mind updating all versions please?

**Comment by kasadaamos** [comment]
> Good addition, would you mind updating all versions please?

Done.

**Comment by kasadaamos** [comment]
> Any reason why we are now using a jsonpath?

To include the namespace in the name of the resource to delete.

**Review by tomkerkhove — APPROVED** [review]
Last request, sorry, can you also update 2.10 please?

**Comment by kasadaamos** [comment]
> Last request, sorry, can you also update 2.10 please?

Done.

**Comment by tomkerkhove** [comment]
Thanks a ton!

**Pull request merged**
