### PR TITLE
chore: Refactor top-level search bar

### PR DESCRIPTION
**Pull request by PixelRobots**
_Provide a description of what has been changed_

Update config.toml to change menu order as in #872 

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Can you fix the DCO issues please? You can learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

**Comment by tomkerkhove** [comment]
@zroubalik @JorTurFer which one do you prefer?
1) Abbreviated
image

2) Full
image

**Comment by PixelRobots** [comment]
> Can you fix the DCO issues please? You can learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

I think that fixed it.

**Comment by PixelRobots** [comment]
> @zroubalik @JorTurFer which one do you prefer?
> 
> 1. Abbreviated
>    image
> 2. Full
>    image

The reason I chose Auth providers is due to the button on the homepage being "Auth providers"

**Comment by JorTurFer** [comment]
As now it'll be a top level button, I prefer it shorter as possible to not taking all the screen just for a button

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Thanks a ton!

**Pull request merged**
