### PR TITLE
Add support for cassandra tls

### PR DESCRIPTION
**Pull request by rxg8255**
_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes: https://github.com/kedacore/keda/issues/5802

### CODE REVIEW

**Review by tomkerkhove — COMMENTED** [review]
LGTM, but would you mind linking the feature PR please?

We can only merge if that one was merged

**Review by zroubalik — COMMENTED** [review]
@rxg8255 I have already merged the feature PR and realised that this docs PR targets 2.14, could you please move the changes to 2.15 and make sure they are up to date with the merged feature? Thanks!

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!

**Comment by zroubalik** [comment]
@rxg8255 could you please include only commit with your changes? (rebase)

**Comment by rxg8255** [comment]
> @rxg8255 could you please include only commit with your changes? (rebase)

Merged all commits to 1

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
