### PR TITLE
WIP - Display list of supported scalers on workload docs

### PR DESCRIPTION
**Pull request by tomkerkhove**
Display list of supported scalers on workload docs to make them more easily discoverable as they are only on our landing page for now.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
I'll have to get this sorted:
image

**Comment by jeffhollan** [comment]
Yeah I played with this a bit before and I don’t reallly want scalers showing at bottom of every docs page. If we create a dedicated section for scalers like we have for auth I’m cool with it but couldn’t figure out how to do that. Other than that would prefer to just like to root page list.

**Comment by jeffhollan** [comment]
Ah looks like you only are trying to show in 2 sections. I’m cool with that if you can get it working

**Comment by tomkerkhove** [comment]
It's just an idea, having them on landing page is ok for me as well!

Let's maybe focus on other things instead of this then?

**Pull request closed without merging**
