### PR TITLE
add Bearer authentication to overview of section authentication parameters

### PR DESCRIPTION
**Pull request by uli-f**
## What has been changed

Added Bearer authentication to overview of section _Authentication Parameters_.

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Nice catch! Could you update v2.14 as well?

**Comment by uli-f** [comment]
> Nice catch! Could you update v2.14 as well?

Sure.

Done in [#2e5888b4418d1f52b946362378b7b3d5d43f5c31](https://github.com/kedacore/keda-docs/pull/1335/commits/2e5888b4418d1f52b946362378b7b3d5d43f5c31)

**Review by JorTurFer — APPROVED** [review]
❤️

**Comment by JorTurFer** [comment]
Could you solve DCO too? You can find all the steps clicking the link
image

**Comment by uli-f** [comment]
> Could you solve DCO too? You can find all the steps clicking the link

Done.

**Pull request merged**
