### PR TITLE
added create namespace flag to helm; kubectl create namespace command can be deleted

### PR DESCRIPTION
**Pull request by raghu-manne**
Removed `kubectl create namespace keda` command  and added `--create-namespace` flag to helm install so that it will create the namespace if doesn't exist.
### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Thanks, could you please add it also to other versions? At least 2.8 2.9 and 2.11? Thanks!

**Comment by raghu-manne** [comment]
@zroubalik Added for all the other versions.

**Comment by tomkerkhove** [comment]
Can you also update 2.12 please?

**Comment by raghu-manne** [comment]
@tomkerkhove 
I didn't notice it since 2.12 is added after i started working on this PR; anyways i made changes to 2.12 as well.

**Comment by raghu-manne** [comment]
@tomkerkhove @zroubalik 
Is this good to merge?

**Review by tomkerkhove — APPROVED** [review]
LGTM

**Comment by tomkerkhove** [comment]
Sorry this fell through the cracks.

**Comment by raghu-manne** [comment]
No issues, thanks for the merge.

**Pull request merged**
