### PR TITLE
🚧 docs: Provide improved side-bar structure

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide improved side-bar structure to have a more consistent experience and ordering that follows how people would adopt KEDA (what, deploy, ops, faq).

**Current:**
image

**Proposal:**
image

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@kedacore/keda-maintainers This proposal is only for 2.9 because I want to verify we want this new structure before I update all versions.

Thoughts?

**Comment by tomkerkhove** [comment]
Still broken as tracked in #https://github.com/kedacore/keda-docs/issues/928

**Review by JorTurFer — APPROVED** [review]

**Comment by tomkerkhove** [comment]
@kedacore/keda-maintainers I forgot about this PR - If you like the proposed changes I can re-do them?

**Review by zroubalik — COMMENTED** [review]
I like the proposal

**Pull request closed without merging**
