### PR TITLE
Clarify that the keda-operator serviceAccount is used for azure workload identity federation

### PR DESCRIPTION
**Pull request by defenestration**
…

_Provide a description of what has been changed_

### Checklist

- [x] Clarify that the keda-operator serviceAccount is used for azure workload identity federation

Fixes N/A

This was not obvious in the existing docs, and I think will be helpful as people migrate off of AADPodIdentity.

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Hi,
Could you update v2.11 as well?

**Comment by defenestration** [comment]
> Hi, Could you update v2.11 as well?

Sure, the latest commit has it.

**Comment by JorTurFer** [comment]
f**k!
Sorry, I missed this PR before the release 🤦 I'm so sorry...
Could you bump your branch and add the change in v2.12? Then we can merge it

**Comment by defenestration** [comment]
Hello, no worries, updated 2.12 doc as well now.

**Comment by JorTurFer** [comment]
The last request 🙏 : Could you add the latest change also to v2.10?

**Comment by defenestration** [comment]
Hello, 2.10 docs have been updated the same as well!

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
@tomkerkhove PTAL

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
